# Generated by Django 4.2.11 on 2024-03-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asesor',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set(),
        ),
    ]
