# Generated by Django 4.2.11 on 2024-05-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cooviahorromonth_court_alter_asesor_cooviahorro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooviahorromonth',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='fileAhorroVista',
        ),
        migrations.AddField(
            model_name='file',
            name='fileComisiones',
            field=models.FileField(default='emply_file.xslx', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='cooviahorromonth',
            name='court',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='file',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
    ]
