# Generated by Django 4.2.11 on 2024-06-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_cooviahorromonth_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fileCrecimientoBase',
            field=models.FileField(default='empty.xlsx', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='file',
            name='fileComisiones',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
