# Generated by Django 4.2.11 on 2024-06-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_file_filecrecimientobase_alter_file_filecomisiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fileAhorroVista',
            field=models.FileField(default='emptyahorro.xlsx', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='fileComisiones',
            field=models.FileField(default='emptycomisiones.xlsx', upload_to='uploads/'),
        ),
    ]
