# Generated by Django 4.2.11 on 2024-06-17 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_file_filecrecimientocdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subzona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subzona', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='asesor',
            name='subzona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subzona'),
        ),
    ]
