# Generated by Django 4.2.11 on 2024-06-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_subzona_asesor_subzona'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fileCrecimientoAhorro',
            field=models.FileField(default='emptyCrecimientoAhorro.xlsx', upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='file',
            name='fileCrecimientoCooviahorro',
            field=models.FileField(default='emptyCrecimientoCooviahorro.xlsx', upload_to='uploads'),
        ),
    ]
