# Generated by Django 4.2.11 on 2024-06-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_crecimientocdatmonth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crecimientocdatmonth',
            options={'ordering': ['-year', '-month']},
        ),
    ]
