# Generated by Django 4.2.11 on 2024-06-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_crecimientocdatmonth_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountCrecimientoCDAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
    ]
