# Generated by Django 4.2.11 on 2024-06-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_asesor_options_crecimientocooviahorromonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountCrecimientoCooviahorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
    ]
