# Generated by Django 4.2.11 on 2024-05-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0005_cdattasas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AhorroVista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueMin', models.CharField(max_length=100)),
                ('valueMax', models.CharField(max_length=100)),
                ('porcentaje', models.FloatField()),
            ],
        ),
    ]
