# Generated by Django 4.2.11 on 2024-06-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0007_cdatcaptaciones'),
        ('tasas', '0007_crecimientobasesocial'),
    ]

    operations = [
    ]
