# Generated by Django 4.2.11 on 2024-06-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0008_merge_0007_cdatcaptaciones_0007_crecimientobasesocial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CdatCaptaciones',
        ),
    ]
