# Generated by Django 4.2.11 on 2024-06-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0010_crecimientocdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrecimientoCooviahorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
