# Generated by Django 4.2.11 on 2024-07-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0012_crecimientoahorrovista'),
    ]

    operations = [
        migrations.CreateModel(
            name='crecimientoCartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('tasaMin', models.FloatField()),
                ('tasaMax', models.FloatField()),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
