# Generated by Django 4.2.11 on 2024-07-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0013_crecimientocartera'),
    ]

    operations = [
        migrations.AddField(
            model_name='crecimientocartera',
            name='valueMax',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='crecimientocartera',
            name='valueMin',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
