# Generated by Django 4.2.11 on 2024-07-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0014_crecimientocartera_valuemax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crecimientocartera',
            name='valueMax',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crecimientocartera',
            name='valueMin',
            field=models.CharField(max_length=100),
        ),
    ]
