# Generated by Django 4.2.11 on 2024-07-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('tasas', '0015_alter_crecimientocartera_valuemax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliaciones',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.roles'),
        ),
    ]
