# Generated by Django 4.2.11 on 2024-07-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0016_alter_afiliaciones_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiliaciones',
            name='description',
        ),
        migrations.RemoveField(
            model_name='afiliaciones',
            name='rol',
        ),
    ]
